services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Copenhagen
      - LANG=en
      - WG_PORT=51820
      - PORT=51821
      - WG_DEFAULT_DNS=1.1.1.1
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1
      - WG_PERSISTENT_KEEPALIVE=0
    env_file:
      - .env

    networks:
      - proxy
    ports:
      #- 51821:51821/tcp
      - 51820:51820/udp
    volumes:
      - etc_wireguard:/etc/wireguard
    labels:
      caddy: "${DASHBOARD_DOMAIN}"
      caddy.reverse_proxy: "{{upstreams 51821}}"
      com.centurylinklabs.watchtower.enable: true

volumes:
  etc_wireguard:

networks:
  proxy:
    external: true