services:
    portainer_agent:
        ports:
            - 9001:9001
        container_name: portainer_agent
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - /:/host
        image: portainer/agent
        environment:
            - TZ=Europe/Copenhagen
        labels:
            com.centurylinklabs.watchtower.enable: true
